spring:
  profiles:
    active: dev
    group:
      dev: dev, common, secret-dev
      dongwan: dongwan-server, common, secret-prod
      seohyun: seohyun-server, common, secret-prod
      dabin: dabin-server, common, secret-prod

---

spring:
  config:
    activate:
      on-profile: dongwan-server

domain:
  name:
    http: http://githib.store
    https: https://githib.store

app:
  cors:
    allowed-origins:
      - "https://githib.store"

---

spring:
  config:
    activate:
      on-profile: seohyun-server

domain:
  name:
    http: http://seohyun.store
    https: https://seohyun.store

app:
  cors:
    allowed-origins:
      - "https://seohyun.store"

---

spring:
  config:
    activate:
      on-profile: dabin-server

domain:
  name:
    http: http://test12345.store
    https: https://test12345.store

app:
  cors:
    allowed-origins:
      - "https://test12345.store"

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: secret-dev
  import:
    optional:
      classpath: application-secret-dev.yml

---

spring:
  config:
    activate:
      on-profile: secret-prod
  import:
    classpath: application-secret-prod.yml

---

spring:
  config:
    activate:
      on-profile: common
  servlet:
    multipart:
      max-file-size: 10MB    # 파일 하나당 크기
      max-request-size: 100MB    # 요청 전체 크기
  data:
    redis:
      host: localhost
      port: 6379

domain:
  name:
    http: http://localhost:80
    https: https://localhost:443

server:
  tomcat:
    max-swallow-size: -1  # 스프링 부트가 주는걸 다 기다리겠다

app:
  base-url: "http://localhost:8080"

springdoc:
  swagger-ui:
    path: doc

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.korit.sa_one_back.entity