spring:
  profiles:
    active: dev
    group:
      dev: dev, common, secret
      local: common, secret

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
<<<<<<< HEAD
      on-profile: secret
    import:
      - classpath:application-secret-dev.yml
      - classpath:application-secret-prod.yml

---

spring:
  config:
    activate:
=======
>>>>>>> origin/main
      on-profile: common
  servlet:
    multipart:
      max-file-size: 10MB    # 파일 하나당 크기
      max-request-size: 100MB    # 요청 전체 크기
  data:
    redis:
      host: localhost
      port: 6379

domain:
  name:
    http: http://localhost:80
    https: https://localhost:443

server:
  tomcat:
    max-swallow-size: -1  # 스프링 부트가 주는걸 다 기다리겠다

app:
  base-url: "http://localhost:8080"

springdoc:
  swagger-ui:
    path: doc

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.korit.sa_one_back.entity