name: GCP-VM-CICD

on:
  push:
    branches: [deploy-dongwan, deploy-dabin, deploy-seohyun]
  pull_request:
    branches: [deploy-dongwan, deploy-dabin, deploy-seohyun]

jobs:
  build-deploy-dongwan:
    runs-on: ubuntu-22.04
    steps:
      - name: set-env
        run: |
          if [ ${{github.ref}} == 'refs/heads/deploy-dongwan' ]; then
          
            echo "GCP_VM_HOST=${{secrets.GCP_VM_HOST_DONGWAN}}" >> $GITHUB_ENV
            echo "GCP_VM_USERNAME=${{secrets.GCP_VM_USERNAME_DONGWAN}}" >> $GITHUB_ENV
            echo "GCP_VM_SSHKEY=${{secrets.GCP_VM_SSHKEY_DONGWAN}}" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME_DONGWAN}}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD_DONGWAN}}" >> $GITHUB_ENV
            echo "APPLICATION_SECRET=${{secrets.APPLICATION_SECRET_DONGWAN}}" >> $GITHUB_ENV
            echo "REACT_ENV=${{secrets.REACT_ENV_DONGWAN}}" >> $GITHUB_ENV
          
          elif [ ${{github.ref}} == 'refs/heads/deploy-seohyun' ]; then

            echo "GCP_VM_HOST=${{secrets.GCP_VM_HOST_SEOHYUN}}" >> $GITHUB_ENV
            echo "GCP_VM_USERNAME=${{secrets.GCP_VM_USERNAME_SEOHYUN}}" >> $GITHUB_ENV
            echo "GCP_VM_SSHKEY=${{secrets.GCP_VM_SSHKEY_SEOHYUN}}" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME_SEOHYUN}}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD_SEOHYUN}}" >> $GITHUB_ENV
            echo "APPLICATION_SECRET=${{secrets.APPLICATION_SECRET_SEOHYUN}}" >> $GITHUB_ENV
            echo "REACT_ENV=${{secrets.REACT_ENV_SEOHYUN}}" >> $GITHUB_ENV

          elif [ ${{github.ref}} == 'refs/heads/deploy-dabin' ]; then

            echo "GCP_VM_HOST=${{secrets.GCP_VM_HOST_DABIN}}" >> $GITHUB_ENV
            echo "GCP_VM_USERNAME=${{secrets.GCP_VM_USERNAME_DABIN}}" >> $GITHUB_ENV
            echo "GCP_VM_SSHKEY=${{secrets.GCP_VM_SSHKEY_DABIN}}" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME_DABIN}}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD_DABIN}}" >> $GITHUB_ENV
            echo "APPLICATION_SECRET=${{secrets.APPLICATION_SECRET_DABIN}}" >> $GITHUB_ENV
            echo "REACT_ENV=${{secrets.REACT_ENV_DABIN}}" >> $GITHUB_ENV

          fi

      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{github.ref}}

      - name: Install JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Springboot Build
        run: |
          cd sa_one_back
          echo ${{env.APPLICATION_SECRET}} | base64 --decode > ./src/main/resources/application-secret-prod.yml
          chmod 777 ./mvnw
          ./mvnw clean package -Dtestskip

      - name: Springboot Docker image build
        run: |
          cd sa_one_back
          docker build -t ${{env.DOCKER_USERNAME}}/springboot-app:latest .

      - name: Springboot Docker image push
        run: |
          echo "${{env.DOCKER_PASSWORD}}" | docker login -u ${{env.DOCKER_USERNAME}} --password-stdin
          docker push ${{env.DOCKER_USERNAME}}/springboot-app:latest

      - name: React Docker image build
        run: |
          cd sa_one_front
          echo ${{env.REACT_ENV}} | base64 --decode > .env
          docker build -t ${{env.DOCKER_USERNAME}}/react-app:latest .

      - name: React Docker image push
        run: |
          docker push ${{env.DOCKER_USERNAME}}/react-app:latest

      - name: GCP SSH REMOTE
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.GCP_VM_HOST}}
          usename: ${{env.GCP_VM_USERNAME}}
          key: ${{env.GCP_VM_SSHKEY}}
          script: |
            cd /home/${{env.GCP_VM_USERNAME}}
            sudo docker compose -f front-compose.yml pull
            sudo docker compose -f back-compose.yml pull
            sudo docker compose -f front-compose.yml down
            sudo docker compose -f front-compose.yml up -d
            sudo docker compose -f back-compose.yml down
            sudo docker compose -f back-compose.yml up -d
        
